#!/usr/bin/expect

set port [lindex $argv 0]
set host [lindex $argv 1]
set passwd [lindex $argv 2]

spawn ssh -NgP -L $port $host

expect {
    "yes/no" { send "yes\r";exp_continue }
    "password:" { send "$passwd\r" }
}

#expect eof
interact
