#!/usr/bin/expect

set command [lindex $argv 0]
set passwd [lindex $argv 1]

spawn ssh $command

expect {
    "yes/no" { send "yes\r";exp_continue }
    "password:" { send "$passwd\r" }
}

#expect eof
interact
